### ISSUE TITLE
Mail is always unavailable after versions upgrade

### ISSUE THREAD

**Issue by shinych** [katzer/cordova-plugin-email-composer#209]
After upgrading cordova-plugin-email-composer to 0.8.3 (Cordova 6.1.1), on Android and iOS the call cordova.plugins.email.isAvailable(fn) always triggers the callback function with "false". In Browser it still works fine.

And another problem (probably not worth a separate ticket):
after downgrade to 0.8.2 the Android works fine, but iOS cannot be built due to:

```
/Users/shinych/dev/git-repos/points.dzg/dzg.ui.phonegap/platforms/ios/build/DZG.build/Debug-iphonesimulator/DZG.build/Objects-normal/i386/APPEmailComposer.dia -c /Users/shinych/dev/git-repos/points.dzg/dzg.ui.phonegap/platforms/ios/DZG/Plugins/de.appplant.cordova.plugin.email-composer/APPEmailComposer.m -o /Users/shinych/dev/git-repos/points.dzg/dzg.ui.phonegap/platforms/ios/build/DZG.build/Debug-iphonesimulator/DZG.build/Objects-normal/i386/APPEmailComposer.o
/Users/shinych/dev/git-repos/points.dzg/dzg.ui.phonegap/platforms/ios/DZG/Plugins/de.appplant.cordova.plugin.email-composer/APPEmailComposer.m:23:9: fatal error: 'Cordova/NSData+Base64.h' file not found
#import "Cordova/NSData+Base64.h"
        ^
1 error generated.

** BUILD FAILED **
```

**Comment by pilladooo** [comment]
I get the error "Uncaught TypeError: fn is not a function" with version 0.8.3 in Android.

**Comment by AlexandraNau** [comment]
I will close this issue, because there are multiple issues regarding the same topic. Please track #211 and #210.
